services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Incubator\MemberManagement\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  TYPO3Incubator\MemberManagement\TCA\TypeMembershipItemsProcFunc:
    public: true
