indexedsearch:
  targetPid: 3
fcbigfoot:
  pages:
    privacy: 2
    contact: 4
  socialmedia:
    channels:
      instagram:
        link: 'https://www.instagram.com/typo3_official/'
memberManagement:
  organization:
    name: 'FC Bigfoot'
    personInCharge: 'Muster Person'
    emailOfPersonInCharge: muster.person@typo3.org
    defaultCountry: 'ES'
    address:
      streetAndHouseNumber: 'Street X 12'
      city: 'La Oliva'
      zip: '11010'
      country: España
    paymentInformation:
      iban: DE75512108001245126199
      bic: AUTOATW1XXX
      paymentDueMonth: '2'
felogin:
  view: 
    templateRootPath: EXT:member_management/Resources/Private/Templates
