name: typo3-incubator/member-management
label: 'Member Management'
settings:
  memberManagement:
    storage:
      membershipsFolderPid: 0
      paymentsFolderPid: 0
    organization:
      name: ''
      personInCharge: ''
      emailOfPersonInCharge: ''
      defaultUsergroup: 1
      address:
        streetAndHouseNumber: ''
        city: ''
        zip: ''
        country: ''
      paymentInformation:
        iban: ''
        bic: ''
        sepaCreditorId: ''
        paymentReason: ''
        paymentDueMonth: ''
